export enum PermissionPermission {
  CREATE_PERMISSION = "CREATE_PERMISSION",
  READ_PERMISSION = "READ_PERMISSION",
  UPDATE_PERMISSION = "UPDATE_PERMISSION",
  DELETE_PERMISSION = "DELETE_PERMISSION",
} 