services:
    bot:
        container_name: elysia-pg-bot
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
        - NODE_ENV=production
    postgres:
            container_name: elysia-pg-postgres
            image: postgres:latest
            restart: unless-stopped
            environment:
                - POSTGRES_USER=elysia-pg
                - POSTGRES_PASSWORD=Please-change-password
                - POSTGRES_DB=elysia-pg
            volumes:
                - postgres_data:/var/lib/postgresql/data
    redis:
            container_name: elysia-pg-redis
            image: redis:latest
            command: [ "redis-server", "--maxmemory-policy", "noeviction" ]
            restart: unless-stopped
            volumes:
                - redis_data:/data
volumes:
    postgres_data:
    redis_data:
    
networks:
    default: {}