services:
  postgres:
    container_name: elysia-pg-dev
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=elysia-pg-dev
      - POSTGRES_PASSWORD=tigatiga
      - POSTGRES_DB=elysia-pg-dev
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: elysia-pg-dev-redis
    image: redis:latest
    command: ["redis-server", "--maxmemory-policy", "noeviction"]
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:

networks:
  default: {}
