import { Data } from "effect"

export enum ApplicationErrorCode {
    EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED",
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
    EMAIL_TOKEN_EXPIRED = "EMAIL_TOKEN_EXPIRED",
    EMAIL_TOKEN_INVALID_FORMAT = "EMAIL_TOKEN_INVALID_FORMAT",
    EMAIL_TOKEN_NOT_FOUND = "EMAIL_TOKEN_NOT_FOUND",
    EMAIL_TOKEN_REJECTED = "EMAIL_TOKEN_REJECTED",
    FAILED_TO_CREATE_EMAIL_VERIFICATION_TOKEN =
        "FAILED_TO_CREATE_EMAIL_VERIFICATION_TOKEN",
    FAILED_TO_CREATE_USER = "FAILED_TO_CREATE_USER",
    FAILED_TO_DELETE_USER = "FAILED_TO_DELETE_USER",
    FAILED_TO_READ_POST = "FAILED_TO_READ_POST",
    FAILED_TO_SEND_EMAIL = "FAILED_TO_SEND_EMAIL",
    FAILED_TO_UPDATE_POST = "FAILED_TO_UPDATE_POST",
    INTERNAL = "INTERNAL",
    INVALID_CREDENTIAL_FORMAT = "INVALID_CREDENTIAL_FORMAT",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    INVALID_USER = "INVALID_USER",
    PAGE_INVALID = "PAGE_INVALID",
    PAGE_NOT_FOUND = "PAGE_NOT_FOUND",
    PASSWORDS_DO_NOT_MATCH = "PASSWORDS_DO_NOT_MATCH",
    PERMISSION_ALREADY_ASSIGNED = "PERMISSION_ALREADY_ASSIGNED",
    PERMISSION_NOT_FOUND = "PERMISSION_NOT_FOUND",
    POST_DELETE_TARGET_NOT_FOUND = "POST_DELETE_TARGET_NOT_FOUND",
    POST_NOT_FOUND = "POST_NOT_FOUND",
    SESSION_ALREADY_EXISTS = "SESSION_ALREADY_EXISTS",
    UNAUTHORIZED = "UNAUTHORIZED",
    UNAUTHORIZED_PERMISSION = "UNAUTHORIZED_PERMISSION",
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_PERMISSION_NOT_FOUND = "USER_PERMISSION_NOT_FOUND",
}

export class ApplicationError extends Data.TaggedError("ApplicationError")<{
    code: ApplicationErrorCode
}> {}

export const applicationError = (code: ApplicationErrorCode) =>
    new ApplicationError({ code })
